### ISSUE TITLE
feature - Add Mode 0 to constants

### ISSUE THREAD

**Issue by oobayly** [max13fr/AirzoneCloudDaikin#2]
We have a [Daikin Heat Reclaim Ventilation VAM](https://www.acsalesdirect.co.uk/Daikin%20VAM%20Range.html) unit, which is causing an error with the library. It has a mode of "0", which isn't in the constants `/AirzoneCloudDaikin/contants.py`

Error:
```
Traceback (most recent call last):
  File "./watch.py", line 14, in <module>
    api = AirzoneCloudDaikin(USER, PASS)
  File "/home/baylyj/.local/lib/python3.6/site-packages/AirzoneCloudDaikin/AirzoneCloudDaikin.py", line 45, in __init__
    self._load_installations()
  File "/home/baylyj/.local/lib/python3.6/site-packages/AirzoneCloudDaikin/AirzoneCloudDaikin.py", line 111, in _load_installations
    installation = Installation(self, installation_data)
  File "/home/baylyj/.local/lib/python3.6/site-packages/AirzoneCloudDaikin/Installation.py", line 24, in __init__
    self._load_devices()
  File "/home/baylyj/.local/lib/python3.6/site-packages/AirzoneCloudDaikin/Installation.py", line 115, in _load_devices
    device = Device(self._api, self, device_data)
  File "/home/baylyj/.local/lib/python3.6/site-packages/AirzoneCloudDaikin/Device.py", line 20, in __init__
    _LOGGER.info("Init {}".format(self.str_complete))
  File "/home/baylyj/.local/lib/python3.6/site-packages/AirzoneCloudDaikin/Device.py", line 37, in str_complete
    self.mode,
  File "/home/baylyj/.local/lib/python3.6/site-packages/AirzoneCloudDaikin/Device.py", line 80, in mode
    return MODES_CONVERTER[self.mode_raw]["name"]
KeyError: '0'
```

A simple solution would be to add a "None" mode:
``` diff
 # 2020-05-23: extracted from website and saved copy in reverse/application.js
 
 MODES_CONVERTER = {
+    "0": {"name": "none", "type": "none", "description": "None"},
     "1": {"name": "cool", "type": "cold", "description": "Cooling mode"},
     "2": {"name": "heat", "type": "heat", "description": "Heating mode"},
     "3": {
```

**Comment by max13fr** [comment]
Hi, thanks for your contribution, just merged & generate a new release.

Max
